### ISSUE TITLE
Downloading WireMock jar from Maven Central failed

### ISSUE THREAD

**Issue by robinpellegrims** [modernweb-pl/wiremock-standalone#1]
When using this library in a Windows environment and a terminal without curl support, the wiremock-standalone jar fails to download on npm install.

Workaround is to use some curl-enabled terminal on windows (like git bash), but it would be interesting to have it working on any chosen terminal.

> error An unexpected error occurred: "C:\\myrepo\node_modules\\wiremock-standalone: Command failed.
> Exit code: 1
> Command: C:\\Windows\\system32\\cmd.exe
> Arguments: /d /s /c node install.js
> Directory: C:\\myrepo\node_modules\\wiremock-standalone
> Output:
> Downloading WireMock standalone from Maven Central...
>   http://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/2.15.0/wiremock-standalone-2.15.0.jar
> C:\\myrepo\node_modules\\wiremock-standalone\\install.js:15
>   throw new Error('Downloading WireMock jar from Maven Central failed');
>   ^
> 
> Error: Downloading WireMock jar from Maven Central failed
>     at Object.<anonymous> (C:\\myrepo\node_modules\\wiremock-standalone\\install.js:15:9)
>     at Module._compile (module.js:662:30)
>     at Object.Module._extensions..js (module.js:673:10)
>     at Module.load (module.js:575:32)
>     at tryModuleLoad (module.js:515:12)
>     at Function.Module._load (module.js:507:3)
>     at Function.Module.runMain (module.js:703:10)

**Comment by Hagith** [comment]
I'm not a huge fan of Windows environment and I do not have an instance to test.
Can you please check if https://github.com/Hagith/wiremock-standalone/pull/2 solves the problem?

Thank you for your contribution.

**Comment by robinpellegrims** [comment]
Not a big fan of Windows either, but company policies appear to be. :-(

#2 seems to solve it, thank you for the quick fix!

**Comment by Hagith** [comment]
You welcome :)
