### ISSUE TITLE
Proxy Config not working

### ISSUE THREAD

**Issue by stephanabel** [modernweb-pl/wiremock-standalone#12]
# Proxy Config not working
Hi @Hagith,

thank you for the updated version of the standalone.
I tried downloading the wiremock via an alternative repo and failed.

It seems that the basepath was changed from `const mavenPath = 'com/github/tomakehurst/wiremock-standalone';` to `const mavenPath = 'maven2/com/github/tomakehurst/wiremock-standalone';` in one of your latest commits.

So the installer tries to download from `<MAVEN_REPO_URL>/maven2/com/github/tomakehurst/wiremock-standalone`.
My proxy sadly provides the artifact under the following url: `<MAVEN_REPO_URL>/maven-central/com/github/tomakehurst/wiremock-standalone` and i have no way to change this.

Is it possible to move the `/maven2`-prefix from the "mavenPath" to the "mavenRepoUrl"?

Thank you and Best Regards
Stephan

**Comment by Hagith** [comment]
published as 3.0.1
