### ISSUE TITLE
Wiremock-standalone install fails upon yarn install when attempting to retrieve the latest wiremock version.

### ISSUE THREAD

**Issue by Duslerke** [modernweb-pl/wiremock-standalone#19]
# Problem:
Upon there being no `MAVEN_...` or `WIREMOCK_VERSION` environment variables specified, the `install.js` script fails with the:
`Error: Cannot read property '1' of null`.

# Cause:

This is because the script attempts to determine the wiremock version from the `maven-metadata.xml` file by the following regex pattern that expects the version between the `release` tags to be **3 dot-separated numbers**:

https://github.com/modernweb-pl/wiremock-standalone/blob/443ee52b109d993e871dcaab4164c7577cba952b/install.js#L28

Presently, the `maven-metadata.xml` file returned has the `release` version specified like so:
``` xml
<release>3.0.0-beta-2</release>
```

This fails the match on the `install.js` **Line 28** pattern, making the `.match(...)` return `null`, finally, causing the error message mentioned above.

# Notes:

Current `maven-metadata.xml` file:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
	<groupId>com.github.tomakehurst</groupId>
	<artifactId>wiremock-standalone</artifactId>
	<versioning>
		<latest>3.0.0-beta-2</latest>
		<release>3.0.0-beta-2</release>
		<versions>
			<version>2.0.1-beta</version>
			... etc (removing all in between to make this shorter)
			<version>2.27.1</version>
			<version>2.27.2</version>
			<version>3.0.0-beta-1</version>
			<version>3.0.0-beta-2</version>
		</versions>
		<lastUpdated>20221230190922</lastUpdated>
	</versioning>
</metadata>
```

Created this Issue ticket, in case a different solution to that of PR #20 is wanted.

**Comment by Hagith** [comment]
Released as [3.1.2](https://github.com/modernweb-pl/wiremock-standalone/releases/tag/v3.1.2)
