### ISSUE TITLE
Can't pass -D options to the java command line

### ISSUE THREAD

**Issue by markgargan** [modernweb-pl/wiremock-standalone#6]
Hi folks, 

I can't seem to pass -D options to the underlying java process that runs the jar from your commandline? I need to pass a custom system variable, say -Dmy.custom.var=localhost:9090? Is this possibly with your module? 

Thanks,
Mark.

**Comment by Hagith** [comment]
Can you please check if #7 is what you need?

**Comment by Hagith** [comment]
Thanks @markgargan for your time :)
Released as 2.25.1-2 and with latest wiremock as 2.26.1-1
