### ISSUE TITLE
Set proxy config

### ISSUE THREAD

**Issue by josluimg** [modernweb-pl/wiremock-standalone#8]
I can't install wiremock due proxy config. I need set a proxy config to download https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-standalone/xxx/wiremock-standalone-xxx.jar

`/node_modules/wiremock-standalone/install.js:37 throw new Error('Downloading WireMock jar from Maven Central failed: ${error}'); ^ Error: Downloading WireMock jar from Maven Central failed: connect ETIMEDOUT 151.101.132.209:443`

I tried setting .nmv/jvm.config
I tried setting HOME/.m2/settings.xml
I tried exporting: 
`export http_proxy=http://x export https_proxy=http://x`

But nothing... I can download from navigator the .jar , even do a curl...

Reading install.js I think it's necessary an option to set proxy setting, because http.get ignore all this options and environment vars...

Terminal: zsh
System: macOS Catalina (10.15.6)
node.js:  12.16.3
npm -v: 6.14.4

**Comment by Hagith** [comment]
Thanks for reporting the issue.

Decided to switch from native `http` to `request` module which [respects proxy settings](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables).
Can you please check if #9 fixes the problem?
